### ISSUE TITLE
`could not find fmt in core` when upgrading to 0.25

### ISSUE THREAD

**Issue by FrancisRussell** [Peternator7/strum#284]
Attempting to upgrade a codebase which compiles with strum 0.24.1 to 0.25.0 (strum_macros at 0.25.1) I get this error when compiling, which seems to be related to the derivation of `EnumIter`.

```
error[E0433]: failed to resolve: could not find `fmt` in `core`
   --> src/cache_cargo_home.rs:524:25
    |
524 |     Debug, Clone, Copy, EnumIter, EnumString, Eq, Hash, PartialEq, IntoStaticStr, Display, Serialize, Deserialize,
    |                         ^^^^^^^^ could not find `fmt` in `core`
    |
    = note: this error originates in the derive macro `EnumIter` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by FrancisRussell** [comment]
OK, I've partly determined what is going wrong here. I have an imported module called `core` which the macro is attempting to access `fmt` out of instead of the top-level core. I guess that previously the same functionality was being accessed via a different path.

It seems like the solution here is to refer to `core` via a `::core` path which should cause it to [access the top-level module](https://doc.rust-lang.org/reference/items/use-declarations.html) regardless of imports..
