### ISSUE TITLE
Does not compile on rust 1.36.0

### ISSUE THREAD

**Issue by axos88** [Peternator7/strum#83]
Although the docs state compatibility with 1.31.0
```
error[E0658]: use of unstable library feature 'iter_nth_back'
   --> src/main.rs:139:75
    |
139 | #[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Hash, EnumIter)]
    |                                                                           ^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/56995

error: aborting due to previous error
```

**Comment by Peternator7** [comment]
That's what I get for losing track of what rustc I have installed. :) Here's a PR to fix it.

#85

**Comment by axos88** [comment]
Shouldn't it be pretty easy to add specific rust versions to the build? That way CI would've caught this.
Thanks for the quick fix. Please let me know when you have it released.

**Comment by Peternator7** [comment]
Published as `0.18.0`. https://crates.io/crates/strum
