### ISSUE TITLE
0.15 breaks Display

### ISSUE THREAD

**Issue by D4nte** [Peternator7/strum#49]
The following piece of code:

```
#[macro_use]
extern crate strum_macros;

#[derive(Clone, Copy, Display, Debug, Serialize)]
#[strum(serialize_all = "snake_case")]
pub enum DataName {
    SecretHash,
    Expiry,
    RedeemIdentity,
    RefundIdentity,
    TokenQuantity,
    TokenContract,
}
```

Compiles with `0.14.0` but does not compile with `0.15.0`:
```
error[E0658]: The attribute `strum` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> vendor/blockchain_contracts/src/lib.rs:16:3
   |
16 | #[strum(serialize_all = "snake_case")]
   |   ^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable
```

```
error: cannot find derive macro `Display` in this scope
  --> vendor/blockchain_contracts/src/lib.rs:15:23
   |
15 | #[derive(Clone, Copy, Display, Debug, Serialize)]
   |    
```

May I suggest to move the readme examples to rust-docs to avoid this kind of issue?

**Comment by Peternator7** [comment]
Thanks for reporting this issue! I'm not able to repro it though :( Could you let me know what version of rustc you're using, and potentially try running `cargo clean` before you build if you've got a little time?

**Comment by D4nte** [comment]
Fine after a cargo clean...

**Comment by D4nte** [comment]
Oh, actually the issue is when running clippy!

```
"cargo" "clippy" "--" "-W" "clippy::cast_possible_truncation" "-W" "clippy::cast_sign_loss" "-W" "clippy::fallible_impl_from" "-W" "clippy::cast_precision_loss" "-W" "clippy::cast_possible_wrap" "-W" "clippy::print_stdout" "-W" "clippy::dbg_macro" "-D" "warnings"
```

```
▶ rustc --version
rustc 1.35.0-nightly (96d700f1b 2019-04-10)
▶ cargo clippy --version
clippy 0.0.212 (37f5c1ec 2019-04-09)
```

**Comment by D4nte** [comment]
To reproduce, check out `864-ethereum-htlc-crate` branch of https://github.com/comit-network/comit-rs

Update strum from `0.14` to `0.15` in `./vendor/blockchain_contracts/Cargo.toml`

run the clippy command above

**Comment by D4nte** [comment]
I upgraded to `nightly-2019-04-30` and it is fine now. Maybe it's just me...

**Comment by D4nte** [comment]
Ok so now it fails on travis: https://travis-ci.com/comit-network/comit-rs/builds/110209768

If you checkout https://github.com/comit-network/comit-rs branch `strum` and run the clippy command: `"cargo" "clippy" "--" "-W" "clippy::cast_possible_truncation" "-W" "clippy::cast_sign_loss"` you should be able to reproduce the issue.

**Comment by Peternator7** [comment]
I think I understand what is happening. This seems like a psuedo-diamond-dependency issue. 

`0.15` added the ability to rename packages using feature flags, and in your repo, [this file](https://github.com/comit-network/comit-rs/blob/5e984b6c03887436a5f0065df6aa2840578b38b5/application/comit_node/Cargo.toml#L38) sets the "verbose-display-name" feature flag which changes the plugin from `Display` to `StrumDisplay`. That appears to be changing the name globally across all your crates.

I was able to set up a tiny repro with 2 crates in the same cargo "workspace." One of them set "verbose-display-name" and the other doesn't. If I call `cargo build` in the root it fails because `Display` cannot be found. If I `cd` into each directory individually though, both build separately. Cargo can't seem to use different combinations of feature flags in the same workspace. 

This seems to be a cargo issue (by design?).

**Comment by D4nte** [comment]
@Peternator7 alright, make sense. Any chance you could push the tiny repo somewhere so we can report the issue to cargo?

**Comment by thomaseizinger** [comment]
> That appears to be changing the name globally across all your crates.

I think, this is actually expected behaviour within cargo/rust. As soon as there is a dependency within your dependency tree that enables a certain feature, you cannot depend on the same dependency without that feature. I am not sure but depending on different versions might work because the result in different binary code.

**Comment by Peternator7** [comment]
I peeked at your code. Macro renaming is mostly for old versions of `rustc`. If you're importing derives by path, you shouldn't need to use them. You can do this:

```
#[derive(Clone, Copy, strum_macros::Display, Debug, Serialize)]
#[strum(serialize_all = "snake_case")]
pub enum DataName {
    SecretHash,
    Expiry,
    RedeemIdentity,
    RefundIdentity,
    TokenQuantity,
    TokenContract,
}
```

**Comment by D4nte** [comment]
Thanks!
