### ISSUE TITLE
Regression: Generating private enum with `EnumDiscriminants` is no longer possible when the parent enum is public

### ISSUE THREAD

**Issue by yescallop** [Peternator7/strum#390]
The following user code is broken by #377:

```rust
#[derive(EnumDiscriminants)]
#[strum_discriminants(name(PrivateDiscriminants), vis(pub(self)))]
pub enum PublicEnum {
    Variant0(bool),
    Variant1 { a: bool },
}
```

With an error message:

```
error[E0446]: private type `PrivateDiscriminants` in public interface
```

This is because the `IntoDiscriminant` impl of `PublicEnum` leaks the private `PrivateDiscriminants` type. Should we maybe exclude the `IntoDiscriminant` impl when the parent enum is public and the generated enum is private?

**Comment by yescallop** [comment]
Thank you! This is confirmed fixed now.
